title: Portfolio Website
description: Welcome! I’m passionate about optimizing supply chains to improve efficiency, reduce costs, and enhance customer satisfaction. This portfolio showcases my skills and projects in logistics, procurement, inventory management, and process improvement. Explore how I turn supply chain challenges into strategic opportunities.
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
